import { useState } from 'react';
import { supabase } from '../lib/supabase';
import { X, Sparkles, Calendar, Clock, CheckCircle, Loader } from 'lucide-react';

export default function AIPlannerModal({ isOpen, onClose, assignments, onSaveTasks }) {
    const [selectedAssignments, setSelectedAssignments] = useState([]);
    const [hoursPerDay, setHoursPerDay] = useState(2);
    const [loading, setLoading] = useState(false);
    const [generatedSchedule, setGeneratedSchedule] = useState(null);
    const [error, setError] = useState(null);

    if (!isOpen) return null;

    const handleGenerate = async () => {
        setLoading(true);
        setError(null);
        try {
            const { data: { session } } = await supabase.auth.getSession();
            const token = session?.access_token;

            if (!token) throw new Error("Please log in.");

            // Filter full assignment objects based on selection
            const assignmentsToPlan = assignments.filter(a => selectedAssignments.includes(a.id));

            if (assignmentsToPlan.length === 0) {
                const msg = "Please select at least one assignment first!";
                alert(msg);
                throw new Error(msg);
            }

            const { data, error } = await supabase.functions.invoke('generate-study-plan', {
                body: {
                    assignments: assignmentsToPlan.map(a => ({
                        id: a.id,
                        title: a.title,
                        dueDate: a.dueDate,
                        priority: 'high' // simplified for now
                    })),
                    hoursPerDay
                },
                headers: {
                    Authorization: `Bearer ${token}`
                }
            });

            if (error) throw error;
            if (data.error) throw new Error(data.error);

            setGeneratedSchedule(data.schedule);

        } catch (err) {
            console.error(err);
            const msg = err.message || 'Failed to generate plan.';
            setError(msg);
            alert(`AI Planner Error: ${msg}`); // Keep error alert for now
        } finally {
            setLoading(false);
        }
    };

    const handleSave = () => {
        if (!generatedSchedule) return;

        // Convert to app task format
        const newTasks = generatedSchedule.map(item => ({
            title: item.title,
            dueDate: item.date,
            estMinutes: item.duration_minutes,
            priority: 'high',
            notes: item.notes || 'Generated by AI'
        }));

        onSaveTasks(newTasks);
        onClose();
    };

    const toggleAssignment = (id) => {
        if (selectedAssignments.includes(id)) {
            setSelectedAssignments(prev => prev.filter(x => x !== id));
        } else {
            setSelectedAssignments(prev => [...prev, id]);
        }
    };

    return (
        <div style={{
            position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
            backgroundColor: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(4px)',
            display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000
        }}>
            <div style={{
                backgroundColor: '#ffffff', // Explicit white for clarity
                color: '#1e293b', // Dark text
                padding: '2rem', borderRadius: '16px',
                width: '90%', maxWidth: '600px', maxHeight: '85vh', overflowY: 'auto',
                boxShadow: '0 20px 50px rgba(0,0,0,0.2)', border: '1px solid rgba(0,0,0,0.1)'
            }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                        <div style={{ padding: '8px', background: '#f3e8ff', borderRadius: '8px' }}>
                            <Sparkles size={24} color="#7c3aed" />
                        </div>
                        <h2 style={{ margin: 0, fontSize: '1.5rem', fontWeight: '700', letterSpacing: '-0.5px' }}>AI Smart Planner</h2>
                    </div>
                    <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#94a3b8', transition: 'color 0.2s' }}>
                        <X size={28} />
                    </button>
                </div>

                {!generatedSchedule ? (
                    <>
                        <p style={{ color: '#64748b', marginBottom: '1.5rem', fontSize: '1rem', lineHeight: '1.5' }}>
                            Select the assignments you want to tackle. Our AI will break them down into manageable study blocks and fit them into your schedule.
                        </p>

                        <h4 style={{ marginBottom: '0.75rem', fontSize: '0.95rem', textTransform: 'uppercase', letterSpacing: '0.5px', color: '#64748b' }}>1. Select Assignments</h4>
                        <div style={{ maxHeight: '250px', overflowY: 'auto', border: '1px solid #e2e8f0', borderRadius: '12px', padding: '0.5rem', marginBottom: '2rem', background: '#f8fafc' }}>
                            {assignments.length === 0 && <p style={{ padding: '1rem', color: '#94a3b8', textAlign: 'center' }}>No pending assignments found.</p>}
                            {assignments.map(a => (
                                <div key={a.id} onClick={() => toggleAssignment(a.id)}
                                    style={{
                                        padding: '1rem', borderBottom: '1px solid #e2e8f0',
                                        display: 'flex', alignItems: 'center', gap: '1rem', cursor: 'pointer',
                                        backgroundColor: selectedAssignments.includes(a.id) ? '#ffffff' : 'transparent',
                                        transition: 'background 0.2s',
                                        borderRadius: '8px'
                                    }}>
                                    <div style={{
                                        width: '24px', height: '24px', borderRadius: '6px',
                                        border: `2px solid ${selectedAssignments.includes(a.id) ? '#7c3aed' : '#cbd5e1'}`,
                                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                                        background: selectedAssignments.includes(a.id) ? '#7c3aed' : 'white'
                                    }}>
                                        {selectedAssignments.includes(a.id) && <CheckCircle size={16} color="white" />}
                                    </div>
                                    <div style={{ flex: 1 }}>
                                        <div style={{ fontWeight: '600', color: '#334155' }}>{a.title}</div>
                                        <div style={{ fontSize: '0.85rem', color: '#64748b', marginTop: '2px' }}>
                                            {(() => {
                                                const d = new Date(a.dueDate);
                                                // Check for invalid, 1970 (epoch), or 1969 (timezone adjusted epoch)
                                                if (isNaN(d.getTime()) || d.getFullYear() < 2000) return <span style={{ color: '#94a3b8' }}>No Due Date</span>;
                                                const isExams = new Date() > d;
                                                return <span style={{ color: isExams ? '#dc2626' : 'inherit' }}>
                                                    {isExams ? 'Overdue: ' : 'Due: '} {d.toLocaleDateString()}
                                                </span>;
                                            })()}
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>

                        <h4 style={{ marginBottom: '0.75rem', fontSize: '0.95rem', textTransform: 'uppercase', letterSpacing: '0.5px', color: '#64748b' }}>2. Study Capacity</h4>
                        <div style={{ marginBottom: '2.5rem', padding: '1.5rem', background: '#f8fafc', borderRadius: '12px', border: '1px solid #e2e8f0' }}>
                            <label style={{ display: 'block', marginBottom: '1rem', color: '#334155', fontWeight: '500' }}>How many hours per day can you study?</label>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
                                <input
                                    type="range" min="1" max="8" step="0.5"
                                    value={hoursPerDay} onChange={(e) => setHoursPerDay(parseFloat(e.target.value))}
                                    style={{ flex: 1, accentColor: '#7c3aed', height: '6px' }}
                                />
                                <div style={{ background: 'white', padding: '0.5rem 1rem', borderRadius: '8px', border: '1px solid #e2e8f0', fontWeight: 'bold', minWidth: '4rem', textAlign: 'center', boxShadow: '0 2px 5px rgba(0,0,0,0.05)' }}>
                                    {hoursPerDay}h
                                </div>
                            </div>
                        </div>

                        {error && (
                            <div style={{ padding: '1rem', backgroundColor: '#fef2f2', border: '1px solid #fee2e2', color: '#b91c1c', borderRadius: '8px', marginBottom: '1.5rem', display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
                                <div style={{ minWidth: '4px', height: '100%', background: '#ef4444', borderRadius: '2px' }}></div>
                                <span>{error}</span>
                            </div>
                        )}

                        <button
                            onClick={handleGenerate}
                            disabled={loading}
                            style={{
                                width: '100%', padding: '1.25rem', borderRadius: '12px', border: 'none',
                                background: loading || selectedAssignments.length === 0 ? '#e2e8f0' : 'linear-gradient(135deg, #7c3aed 0%, #ec4899 100%)',
                                color: loading || selectedAssignments.length === 0 ? '#94a3b8' : 'white',
                                fontWeight: '700', fontSize: '1.1rem',
                                cursor: loading ? 'not-allowed' : 'pointer',
                                display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.75rem',
                                boxShadow: loading || selectedAssignments.length === 0 ? 'none' : '0 4px 15px rgba(124, 58, 237, 0.3)',
                                transition: 'all 0.2s',
                                transform: loading ? 'none' : 'translateY(-1px)'
                            }}
                        >
                            {loading ? <><Loader className="spin" size={24} /> Generating Study Plan...</> : <><Sparkles size={24} /> Generate My Schedule</>}
                        </button>
                    </>
                ) : (
                    <>
                        <div style={{ marginBottom: '2rem' }}>
                            <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
                                <div style={{ width: '60px', height: '60px', background: '#dcfce7', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1rem' }}>
                                    <CheckCircle size={32} color="#16a34a" />
                                </div>
                                <h3 style={{ margin: 0, color: '#166534', fontSize: '1.5rem' }}>Plan Ready!</h3>
                                <p style={{ color: '#64748b', marginTop: '0.5rem' }}>We've broken down your work into manageable sessions.</p>
                            </div>

                            <div style={{ maxHeight: '350px', overflowY: 'auto', border: '1px solid #e2e8f0', borderRadius: '12px', background: '#f8fafc' }}>
                                {generatedSchedule.map((item, idx) => (
                                    <div key={idx} style={{ padding: '1rem 1.5rem', borderBottom: '1px solid #e2e8f0', display: 'flex', gap: '1.25rem', backgroundColor: 'white' }}>
                                        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', minWidth: '60px', padding: '0.5rem', background: '#f1f5f9', borderRadius: '8px', height: 'fit-content' }}>
                                            <Calendar size={18} color="#64748b" />
                                            <span style={{ fontSize: '0.85rem', marginTop: '4px', fontWeight: '600', color: '#475569' }}>{item.date.slice(5)}</span>
                                        </div>
                                        <div style={{ flex: 1 }}>
                                            <div style={{ fontWeight: '600', color: '#1e293b', fontSize: '1.05rem' }}>{item.title}</div>
                                            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', fontSize: '0.9rem', color: '#64748b', marginTop: '6px' }}>
                                                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                                    <Clock size={14} /> {item.duration_minutes} min
                                                </div>
                                                {item.notes && (
                                                    <div style={{ background: '#e0f2fe', color: '#0369a1', padding: '2px 8px', borderRadius: '12px', fontSize: '0.8rem' }}>
                                                        {item.notes}
                                                    </div>
                                                )}
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        <div style={{ display: 'flex', gap: '1rem', paddingTop: '1rem', borderTop: '1px solid #e2e8f0' }}>
                            <button
                                onClick={() => setGeneratedSchedule(null)}
                                style={{
                                    flex: 1, padding: '1rem', borderRadius: '12px', border: '1px solid #e2e8f0',
                                    background: 'white', color: '#475569', cursor: 'pointer', fontWeight: '600',
                                    fontSize: '1rem'
                                }}
                            >
                                Back
                            </button>
                            <button
                                onClick={handleSave}
                                style={{
                                    flex: 2, padding: '1rem', borderRadius: '12px', border: 'none',
                                    background: '#16a34a', color: 'white', fontWeight: 'bold', cursor: 'pointer',
                                    fontSize: '1rem', boxShadow: '0 4px 12px rgba(22, 163, 74, 0.2)'
                                }}
                            >
                                Accept & Add to Planner
                            </button>
                        </div>
                    </>
                )}
            </div>
            <style>{`
                .spin { animation: spin 1s linear infinite; }
                @keyframes spin { 100% { transform: rotate(360deg); } }
                /* Custom Scrollbar for the list */
                ::-webkit-scrollbar { width: 6px; }
                ::-webkit-scrollbar-track { background: transparent; }
                ::-webkit-scrollbar-thumb { background: #cbd5e1; borderRadius: 3px; }
            `}</style>
        </div>
    );
}
